test:
	g++ part1.cpp -o part1
	cat test.txt | ./part1

run:
	g++ part1.cpp -o part1
	cat input.txt | ./part1

run2:
	g++ part2.cpp -o part2
	cat input.txt | ./part2

test2:
	g++ part2.cpp -o part2
	cat test.txt | ./part2